# Render Blueprint for API Gateway Application
services:  
  # API Gateway web service
  - type: web
    name: api-gateway
    runtime: docker
    plan: free 
    region: oregon    
    dockerfilePath: ./ApiGatewayApp/ApiGatewayApp/Dockerfile
    dockerContext: .
    numInstances: 1
    healthCheckPath: /    
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production      
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: OTEL_EXPORTER_ENDPOINT
        value: https://jaeger-pjqc.onrender.com:4317
      - key: OTEL_EXPORTER_OTLP_PROTOCOL
        value: grpc
      - key: DOTNET_SYSTEM_NET_HTTP_SOCKETSHTTPHANDLER_HTTP2UNENCRYPTEDSUPPORT
        value: true
      - key: ASPNETCORE_FORWARDEDHEADERS_ENABLED
        value: true
      - fromGroup: api-gateway-config
  # Jaeger service for distributed tracing
  - type: web # will be open to the public internet
    name: jaeger
    runtime: image
    image:
      url: jaegertracing/all-in-one:latest
    plan: free
    region: oregon # Must match the region of the API Gateway service
    envVars:
      - key: COLLECTOR_ZIPKIN_HOST_PORT
        value: :9411
      - key: COLLECTOR_OTLP_ENABLED
        value: "true"
    ports:
      - port: 4317
        protocol: TCP
      - port: 4318
        protocol: HTTP  
      - port: 16686
        protocol: HTTP
    autoDeploy: false # Prevents unnecessary Jaeger redeployments

# Environment variable groups for shared configuration
envVarGroups:
  - name: api-gateway-config
    envVars:
      - key: DOTNET_ENVIRONMENT
        value: Production
      - key: LOGGING_LEVEL
        value: Information