services:
  apigatewayapp:
    image: ${DOCKER_REGISTRY-}apigatewayapp
    build:
      context: .
      dockerfile: ApiGatewayApp/Dockerfile
    environment:
      - OTEL_EXPORTER_ENDPOINT=http://jaeger:4317
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_SYSTEM_NET_HTTP_SOCKETSHTTPHANDLER_HTTP2UNENCRYPTEDSUPPORT=true
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"
